# Generated by Django 4.2 on 2023-04-09 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_session_participants_alter_session_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='slug',
            field=models.UUIDField(default=uuid.UUID('ad9b8792-235d-4e8d-b105-f538b0b19636'), primary_key=True, serialize=False),
        ),
    ]
