# Generated by Django 4.2 on 2023-04-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_session_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='points',
            new_name='param1',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='of',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='param2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='param3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
