# Generated by Django 4.2 on 2023-04-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_rename_points_feedback_param1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='of',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='param1',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='param2',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='param3',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
