# Generated by Django 4.2 on 2023-04-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='id')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(choices=[('ST', 'Student'), ('CP', 'Company')], max_length=2)),
                ('company', models.CharField(default='')),
                ('university', models.CharField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='id_image',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.idimage'),
        ),
    ]
