version: '3'

services:
  api:
    image: snickers/learnify
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "8376:8376"
    volumes:
      - ./api/static/:/app/api/static/
      - ./logs/:/app/logs/
      - ./api/media/:/app/api/media/
    network_mode: host
